"""
See documentation/notes/colours.md

``divergent_colors`` are R-style CIE HChL divergent.
"""
feijoa = '#AED882'
divergent_colors = {1:  ['#AED882'],
                    2:  ['#AED882',
                         '#E9B9FF'],
                    3:  ['#AED882',
                         '#81D5FF',
                         '#FFAFD0'],
                    4:  ['#AED882',
                         '#48DEE9',
                         '#E9B9FF',
                         '#FFB7AA'],
                    5:  ['#AED882',
                         '#3FE1D5',
                         '#B0CAFF',
                         '#FFAFEB',
                         '#FEBD94'],
                    6:  ['#AED882',
                         '#4BE2C7',
                         '#81D5FF',
                         '#E9B9FF',
                         '#FFAFD0',
                         '#F5C287'],
                    7:  ['#AED882',
                         '#58E1BC',
                         '#5EDBF5',
                         '#C3C5FF',
                         '#FFB1F4',
                         '#FFB3BA',
                         '#EDC580'],
                    8:  ['#AED882',
                         '#63E1B4',
                         '#48DEE9',
                         '#9FCFFF',
                         '#E9B9FF',
                         '#FFAEE1',
                         '#FFB7AA',
                         '#E7C87C'],
                    9:  ['#AED882',
                         '#6BE0AE',
                         '#3FE0DE',
                         '#81D5FF',
                         '#CCC2FF',
                         '#FEB2F9',
                         '#FFAFD0',
                         '#FFBA9D',
                         '#E2CA79'],
                    10: ['#AED882',
                         '#72E0A9',
                         '#3FE1D5',
                         '#68DAF9',
                         '#B0CAFF',
                         '#E9B9FF',
                         '#FFAFEB',
                         '#FFB2C1',
                         '#FEBD94',
                         '#DDCB78'],
                    11: ['#AED882',
                         '#78DFA5',
                         '#44E1CD',
                         '#55DDF1',
                         '#97D1FF',
                         '#D2C1FF',
                         '#FBB3FC',
                         '#FFAFDC',
                         '#FFB4B4',
                         '#F9C08D',
                         '#DACD77'],
                    12: ['#AED882',
                         '#7DDFA1',
                         '#4BE2C7',
                         '#48DEE9',
                         '#81D5FF',
                         '#BBC7FF',
                         '#E9B9FF',
                         '#FFB0F1',
                         '#FFAFD0',
                         '#FFB7AA',
                         '#F5C287',
                         '#D6CE77'],
                    13: ['#AED882',
                         '#81DF9F',
                         '#51E1C1',
                         '#41E0E1',
                         '#6ED9FB',
                         '#A6CDFF',
                         '#D6BFFF',
                         '#F8B4FE',
                         '#FFAFE5',
                         '#FFB1C4',
                         '#FFB9A1',
                         '#F1C483',
                         '#D4CF76'],
                    14: ['#AED882',
                         '#84DE9C',
                         '#58E1BC',
                         '#3EE1DB',
                         '#5EDBF5',
                         '#92D2FF',
                         '#C3C5FF',
                         '#E9B9FF',
                         '#FFB1F4',
                         '#FFAFDA',
                         '#FFB3BA',
                         '#FFBB9A',
                         '#EDC580',
                         '#D1CF76'],
                    15: ['#AED882',
                         '#87DE9A',
                         '#5DE1B8',
                         '#3FE1D5',
                         '#52DDEF',
                         '#81D5FF',
                         '#B0CAFF',
                         '#D9BEFF',
                         '#F6B4FF',
                         '#FFAFEB',
                         '#FFAFD0',
                         '#FFB5B1',
                         '#FEBD94',
                         '#EAC77E',
                         '#CFD077'],
                    16: ['#AED882',
                         '#8ADE99',
                         '#63E1B4',
                         '#42E1D0',
                         '#48DEE9',
                         '#71D8FC',
                         '#9FCFFF',
                         '#C8C4FF',
                         '#E9B9FF',
                         '#FFB1F7',
                         '#FFAEE1',
                         '#FFB1C6',
                         '#FFB7AA',
                         '#FBBF8F',
                         '#E7C87C',
                         '#CDD177'],
                    17: ['#AED882',
                         '#8CDD97',
                         '#67E1B1',
                         '#46E1CB',
                         '#42DFE3',
                         '#64DAF7',
                         '#8FD2FF',
                         '#B8C8FF',
                         '#DBBEFF',
                         '#F5B5FF',
                         '#FFB0EF',
                         '#FFAFD8',
                         '#FFB2BE',
                         '#FFB8A3',
                         '#F8C18B',
                         '#E4C97A',
                         '#CCD177'],
                    18: ['#AED882',
                         '#8EDD96',
                         '#6BE0AE',
                         '#4BE2C7',
                         '#3FE0DE',
                         '#59DCF2',
                         '#81D5FF',
                         '#A9CCFF',
                         '#CCC2FF',
                         '#E9B9FF',
                         '#FEB2F9',
                         '#FFAFE6',
                         '#FFAFD0',
                         '#FFB4B6',
                         '#FFBA9D',
                         '#F5C287',
                         '#E2CA79',
                         '#CAD177'],
                    19: ['#AED882',
                         '#90DD94',
                         '#6FE0AB',
                         '#4FE2C3',
                         '#3EE1D9',
                         '#50DDED',
                         '#74D8FD',
                         '#9AD0FF',
                         '#BEC7FF',
                         '#DCBDFF',
                         '#F4B5FF',
                         '#FFB0F2',
                         '#FFAEDE',
                         '#FFB0C8',
                         '#FFB5B0',
                         '#FFBC98',
                         '#F2C384',
                         '#DFCB78',
                         '#C9D278'],
                    20: ['#AED882',
                         '#91DD93',
                         '#72E0A9',
                         '#54E1BF',
                         '#3FE1D5',
                         '#48DEE9',
                         '#68DAF9',
                         '#8DD3FF',
                         '#B0CAFF',
                         '#CFC1FF',
                         '#E9B9FF',
                         '#FCB3FB',
                         '#FFAFEB',
                         '#FFAFD7',
                         '#FFB2C1',
                         '#FFB7AA',
                         '#FEBD94',
                         '#F0C482',
                         '#DDCB78',
                         '#C7D278']}
